# Generated by Django 5.2.10 on 2026-02-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_transaction_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='choices',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
    ]
