# Generated by Django 5.2.10 on 2026-02-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_transaction_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
